### ISSUE TITLE
code currently violates the NCBI Entrez User Requirements

### ISSUE THREAD

**Issue by marade** [art-egorov/uorf4u#2]
> Bio.Entrez.email = "anonymous@mail.se"

Use of an anonymous e-mail address is specifically prohibited:

http://biopython.org/DIST/docs/tutorial/Tutorial.html#sec144

https://www.ncbi.nlm.nih.gov/books/NBK25497/

**Comment by art-egorov** [comment]
Hi,
We sent a request to the NCBI for tool registration with  our tool's e-mail. In versions 0.6.3+ we set the tool's e-mail as default; In addition, a user can set their own e-mail with config file.
